services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendAJG
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebAJG
    container_name: frontendAJG

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendAJG
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebAJG
    container_name: backendAJG

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebAJG
    ports:
      - "80:80" # Si tienes problemas con el puerto 80 cambia el puerto externo aquí
    networks:
      - redwebAJG
    container_name: webAJG

networks:
  redwebAJG:
    driver: bridge
